name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build app
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
          - os: windows-2022
    steps:
      - name: Install tk on ubuntu
        if: ${{ matrix.config.os == 'ubuntu-22.04'}}
        run: |
          sudo apt-get update
          sudo apt-get install xclip
          sudo apt install gnome-screenshot
          sudo apt install python3-tk python3-dev python3-setuptools tcl python3-pil python3-pil.imagetk

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install dependencies for ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip
          pip install -r Pipfile
          pip install pyinstaller

      - name: Build with pyinstaller for ${{ matrix.config.os }}
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: pyinstaller main.py --onefile --noconsole --name FD4D --icon="./assets/Images/Logo.png" --add-data "./assets:./assets"
          windows: pyinstaller main.py --onefile --noconsole --name FD4D --icon="./assets/Images/Logo.ico" --add-data "./assets;./assets"

      - name: Rename builded app
        run: mv ./dist ./dist-${{ matrix.config.os }}

      - name: Upload result job ${{ matrix.config.os }}
        uses: actions/upload-artifact@v4
        with:
          name: FD4D-pyinstaller-artifact-${{ matrix.config.os }}
          path: ./dist*
          if-no-files-found: error 
          overwrite: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts ubuntu
        uses: actions/download-artifact@v4
        with:
          name: FD4D-pyinstaller-artifact-ubuntu-22.04
          path: dist-ubuntu-22.04
          
      - name: Download artifacts windows
        uses: actions/download-artifact@v4  
        with:
          name: FD4D-pyinstaller-artifact-windows-2022
          path: dist-windows-2022

      - name: Zip file windows
        run: cd dist-windows-2022 && zip -r ../FD4D_windows.zip .

      - name: Zip file ubuntu
        run: cd dist-ubuntu-22.04 && zip -r ../FD4D_ubuntu.zip .


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            FD4D_windows.zip
            FD4D_ubuntu.zip